const langCode = window.navigator.language || window.navigator.userLanguage;
const langFormat = new Intl.DateTimeFormat(langCode);
const langName = langFormat.resolvedOptions().locale.split("-")[0];
const langMap = {
    "af": "Afrikaans",
    "ar": "Arabic",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "el": "Greek",
    "en": "English",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Farsi",
    "fi": "Finnish",
    "fo": "Faeroese",
    "fr": "French",
    "ga": "Irish",
    "gd": "Gaelic",
    "he": "Hebrew",
    "hi": "Hindi",
    "hr": "Croatian",
    "hu": "Hungarian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ji": "Yiddish",
    "ja": "Japanese",
    "kk": "Kazakh",
    "ko": "Korean",
    "ku": "Kurdish",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "ml": "Malayalam",
    "ms": "Malaysian",
    "mt": "Maltese",
    "nl": "Dutch",
    "no": "Norwegian",
    "pa": "Punjabi",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "rm": "Rhaeto-Romanic",
    "ru": "Russian",
    "sb": "Sorbian",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sr": "Serbian",
    "sv": "Swedish",
    "th": "Thai",
    "tn": "Tswana",
    "tr": "Turkish",
    "ts": "Tsonga",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ve": "Venda",
    "vi": "Vietnamese",
    "xh": "Xhosa",
    "zh": "Chinese",
    "zu": "Zulu",
};

const language = langMap[langName] || "English";

document.getElementById("current-lang-frame").innerHTML = langName;
document.getElementById("current-lang").innerHTML = langName;
document.getElementById("current-lang-full").innerHTML = language;